[tool.poetry]
name = "sd-cliff-vis"
version = "0.1.0"
description = "Coastal LiDAR time series viewer"

[tool.poetry.dependencies]
python = "^3.10"
laspy = "^2.5"
numpy = "^1.24"
tqdm = "^4.65"
boto3 = "^1.28"
python-dotenv = "^1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
